const ENGLISH_DICTIONARY_COLLECTION = "englishDuctionary";
const RUSSIAN_DICTIONARY_COLLECTION = "russianDuctionary";
const VOCABULARY_COLLECTION = "vocaulary";

export {
  ENGLISH_DICTIONARY_COLLECTION,
  RUSSIAN_DICTIONARY_COLLECTION,
  VOCABULARY_COLLECTION,
};
